package storage

import (
	"time"

	"gorm.io/gorm"
)

// SMCTradeLog stores every SMC signal generated by the system + its outcome.
// Trades start as OPEN and get closed when SL/TP/EOD is hit.
type SMCTradeLog struct {
	ID          uint           `gorm:"primarykey" json:"id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"index" json:"-"`

	// Signal metadata
	GeneratedAt time.Time `gorm:"index"  json:"generated_at"`
	Timeframe   string    `gorm:"index"  json:"timeframe"`    // "5m" | "15m"
	Direction   string    `gorm:"index"  json:"direction"`    // "CE" | "PE"
	HTFBias     string    `json:"htf_bias"`
	SweepType   string    `json:"sweep_type"`                 // "HIGH" | "LOW"
	SweepPrice  float64   `json:"sweep_price"`
	FVGLow      float64   `json:"fvg_low"`
	FVGHigh     float64   `json:"fvg_high"`

	// Trade levels
	Entry      float64 `json:"entry"`
	StopLoss   float64 `json:"stop_loss"`
	Target     float64 `json:"target"`
	RiskReward float64 `json:"risk_reward"`

	// Risk plan snapshot
	AccountSize     float64 `json:"account_size"`
	RiskPct         float64 `json:"risk_pct"`
	SuggestedLots   int     `json:"suggested_lots"`
	MaxLossINR      float64 `json:"max_loss_inr"`
	TargetGainINR   float64 `json:"target_gain_inr"`

	// Outcome
	Status     string     `gorm:"index" json:"status"`        // "OPEN" | "WIN" | "LOSS" | "EOD"
	ClosedAt   *time.Time `json:"closed_at"`
	ExitPrice  float64    `json:"exit_price"`
	PnLPct     float64    `json:"pnl_pct"`
	PnLINR     float64    `json:"pnl_inr"`
	BarsHeld   int        `json:"bars_held"`

	// Context tags (for learning)
	Killzone   string `json:"killzone"`         // "KZ1" | "KZ2" | "KZ3"
	DayOfWeek  string `json:"day_of_week"`      // "Mon" | "Tue" ...
	HourBucket int    `json:"hour_bucket"`      // 9-15

	Notes string `json:"notes"`
}

// SMCStats aggregates trade outcomes by various dimensions for the learning dashboard.
type SMCStats struct {
	Total        int     `json:"total"`
	Open         int     `json:"open"`
	Wins         int     `json:"wins"`
	Losses       int     `json:"losses"`
	EODs         int     `json:"eods"`
	WinRate      float64 `json:"win_rate"`
	ProfitFactor float64 `json:"profit_factor"`
	TotalPnLPct  float64 `json:"total_pnl_pct"`
	TotalPnLINR  float64 `json:"total_pnl_inr"`
	AvgWinPct    float64 `json:"avg_win_pct"`
	AvgLossPct   float64 `json:"avg_loss_pct"`
}
